config/routes.rb
NaganoComfortInn::Application.routes.draw do
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations'}

  namespace :gestion do
    resources :users, only: [:show, :index, :new, :create]  do
      resources :reservations, only: [:index], controller: "users/reservations"
    end

    resources :reservations, only: [:index, :new, :create], controller: "reservations"

    resources :rooms, only: [:index]
    resources :room_types, only: [:index, :new, :create]
    resources :view_types, only: [:index, :new, :create]
  end

  namespace :client do
    resources :profiles, only: [:show, :edit, :update]

    resources :reservations, only: [:index, :create, :new, :edit, :update] do
      resources :room_reservations, only: [:edit, :index, :update, :create], controller: "reservations/room_reservations"
    end
  end

  resources :rooms, only: [:show, :index]

  root to: 'pages_generale#home'

  match '/home', to: 'client/profiles#show'
  match '/new_reservation', to: 'client/reservations#new'
  match '/my_reservation', to: 'client/reservations/room_reservations#index'
  match '/my_reservations', to: 'client/reservations#index'
end

app/models/reservation.rb
# == Schema Information
#
# Table name: reservations
#
#  id             :integer          not null, primary key
#  client_demands :string(255)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  user_id        :integer
#  nb_rooms       :integer
#

class Reservation < ActiveRecord::Base
  attr_accessible :client_demands, :nb_rooms, :user_id

  belongs_to :user
  has_many :room_reservations, dependent: :destroy
  has_many :rooms, through: :room_reservations

  validates :user_id, presence: true

  default_scope order: 'reservations.id DESC'


  def reserve_room!(room)
    room_reservations.create!(room_id: room.id)
  end

end

app/controllers/client/client_controller.rb
class Client::ClientController < ApplicationController
  #Ce controller existe pour la répartitions des authorisations d'accès
end	

app/controllers/client/profiles_controller.rb
class Client::ProfilesController < Client::ClientController

  before_filter :set_user

  def edit

  end

  def update
    # update code
  end

  private
    def set_user # duplicate // should be centralized
        @user = current_user
    end
end

app/controllers/client/reservations/room_reservations_controller.rb
module Client
	class Reservations::RoomReservationsController < ReservationsController

	  def show

	  end

	  def index
			puts
			@reservation = Reservation.find(params[:id])
			@room_reservations = @reservation.room_reservations

			respond_to do |format|
				format.html
				format.js {render partial: "client/reservations/room_reservations/edit"}
			end
	  end

		def edit

			respond_to do |format|
				format.html
				format.js {render partial: "client/reservations/room_reservations/edit"}
			end
		end
	end
end

app/controllers/client/reservations_controller.rb
class Client::ReservationsController < Client::ClientController
  before_filter :set_user #Nécessaire??

  def show
    @reservation = Reservation.find(@user.id)
  end

  def index
    @reservation = Reservation.find_all_by_user_id(@user.id)
  end

  def new
    puts "NEW PARAMS : "
    puts params

    @errors = {}
    @rooms = []
    @cpt_steps = init_steps(params)
    @chosen_rooms = get_rooms_from_params(params, :room)
    @check_in = get_value_from_params(params, :check_in)
    @check_out = get_value_from_params(params, :check_out)
    @nb_rooms = get_value_from_params(params, :nb_rooms)
    @demands = get_value_from_params(params, :demands)

    @view_types = get_types_from_params(params, :view_types)
    @room_types = get_types_from_params(params, :room_types)

    @errors[:dates] = validate_dates(@check_in, @check_out) #APPROFONDIR

    if (@cpt_steps >= 3) #CONSTANTE! // faire methode
      @nb_rooms.times do |i|
        @rooms.push(find_possible_rooms(@check_in, @check_out, @view_types[i], @room_types[i]))
      end
    end

    respond_to do |format|
      format.html { }
      format.js {
        render partial: "new", cpt_steps: @cpt_steps, nb_rooms: @nb_rooms
      }
    end
  end

  def create
    puts "CREATE PARAMS : "
    puts params

    chosen_rooms = params[:rooms].split(" ")

    respond_to do |format|

      if chosen_rooms != nil
        @reservation = current_user.reservations.build({nb_rooms: chosen_rooms.count, client_demands: params[:demands]})

        chosen_rooms.each do |r|
          @reservation.room_reservations.build(room_id: r, start_date: params[:check_in], end_date: params[:check_out])
        end

        if @reservation.save
          format.html { redirect_to home_path(notice: 'NEW RESERVATION ADDED') }
          format.js {}
        else
          format.html { render home_path(notice: 'ERROR! RESERVATION CANCELLED!') }
          format.js
        end

      else
        render "new"
      end
    end
  end

  def edit
    @reservation = Reservation.find(params[:id])
  end

  def update

  end

  def set_user 
    @user = current_user
  end



  # # # #
  # Private methods
  # # # #
  private

    def init_steps(params) # faire validation + messages de gestion
      cpt = 0

      if params[:cpt_steps] != nil
        cpt = params[:cpt_steps].to_i

        if params[:commit] == "NEXT"
          cpt += 1
        elsif params[:commit] == "BACK"
          if cpt > 0
            cpt -= 1
          end
        end
      end

      cpt
    end


      ################# regrouper ####################
    def get_value_from_params(params, key)
      info = nil

      if params[key.to_sym] != nil
        if key == :check_in || key == :check_out
          info = params[key.to_sym].to_date
        elsif key == :nb_rooms || key == :room_type || key == :view_type
          info = params[key.to_sym].to_i
        else
          info = params[key.to_sym]
        end
      end

      if info.nil?
        if key == :nb_rooms
          info = 0
        elsif key == :view_type || key == :room_type
          info = 1
        end
      end

      info
    end

    def get_types_from_params(params, key) # faire passer par get_value_from_params
      info = []
      types = params[:types]

      if types != nil
        types.each do |t|
          temp = t[1]
          if key == :room_types
            info.push (temp[:room_type].to_i)
          elsif key == :view_types
            info.push (temp[:view_type].to_i)
          end
        end
      end

      info
    end

  def get_rooms_from_params(params, key) # faire passer par get_value_from_params
    info = []
    rooms = params[:rooms]

    if rooms != nil
      rooms.each do |t|
        temp = t[1]
        info.push (temp[key.to_sym].to_i)
      end
    end

    info
  end

#########################################################

    def find_rooms(rooms)
      missing_room = false
      chosen_rooms = []

      rooms.each do |room|
        if !missing_room
          chosen_room = find_room_basic(room, chosen_rooms)
          missing_room = (chosen_room == nil)
          chosen_rooms.push(chosen_room)
        end
      end

      if missing_room
        nil
      else
        chosen_rooms
      end
    end

    # IMPLEMENTER LA SELECTION SELON CHAMBRES DEJA CHOISIE
    def find_possible_rooms(check_in, check_out, view_type, room_type)
      possible_rooms = []
      possible_rooms_date = []

      # convertir les params en dates
      arrival = check_in
      depart = check_out

      # Touver toutes les chambres ayant le bon ViewType et RoomType
      possible_rooms = Room.view_types(view_type).room_types(room_type)

      # Verif simple de la date de debut de réservation   /  A RETRAVAILLER!!!!
      possible_rooms.each do |possible_room|
        chambre_dispo = true

        # Si le nombre de réservation accrocher à la chambre est plus grand que 0
        if possible_room.room_reservations.count > 0
          possible_room.room_reservations.each do |rr|

            # si la date d'arrivée est plus tard que les dates de réservation de la chambre
            chambre_dispo = date_validation_room_selection(rr, arrival, depart)
          end

          # Si la chambre est disponible (voir CHECK DATE)
          if chambre_dispo == true
            possible_rooms_date.push(possible_room)
          end

        else
          possible_rooms_date.push(possible_room)
        end
      end

      # Retourne un tableau de plusieurs chambres valides
      return possible_rooms_date
    end

    # Valide si la chambre est libre selon les dates de check-in et check-out
    def date_validation_room_selection(room_reservation, check_in, check_out) # A completer
      is_valid = false
      limit_date = room_reservation.start_date + 7.days

      if room_reservation.start_date.to_date < check_in && room_reservation.end_date.to_date < check_in ||
          room_reservation.start_date.to_date > check_out && room_reservation.end_date.to_date > check_out
        is_valid = true

      #elsif room_reservation.start_date.to_date > arrival # gérer les 7 jours
      end

      is_valid
    end

    def validate_dates(check_in, check_out) 
      is_valid = false
      current = Date.current

      if check_in != nil && check_out != nil

        if check_in >= current && current < check_out && check_in < check_out
          is_valid = true
        end
      end

      is_valid
      puts "VALIDATION DATES!"
      puts is_valid
    end

end

app/controllers/gestion/reservations/room_reservations_controller.rb
class Reservation::RoomReservationsController < Gestion::ReservationsController

  def show

  end

  def index

  end
end

app/controllers/gestion/reservations_controller.rb
class Gestion::ReservationsController < Gestion::GestionController
  before_filter :set_user

  def index
    if (@user == nil)
      @reservation = Reservation.all
    else
      @reservation= []
      @user.reservations.all.each do |r|
        @reservation.push r.room_reservations.all
      end
    end

  end

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.create(build_params(params))

    if @reservation.save
      flash[:success] = "NEW RESERVATION ADDED"

      redirect_to gestion_reservations_path
    else
      render 'new'
    end
  end

  def set_user  #temp
    id = params[:user_id]

    if (id != nil)
      @user = User.find(params[:user_id])
    else
      @user = nil
    end

  end

  private
    def build_params(params)
      params_reservation= params[:reservation]
      id = User.find_by_email(params_reservation[:user_id]).id

      params_reservation[:user_id] = id

      return params_reservation
    end
end

app/controllers/gestion/users/reservations_controller.rb
module Gestion
  class Users::ReservationsController < UsersController
    before_filter :set_user

    def show
      @reservation = Reservation.find(params[:id])
    end

    def index
      @reservation = @user.reservations.all
    end

    def new
      @reservation = Reservation.new(user_id: @user.id)
      @room = Room.new
    end

    def create
      puts "test"
      build_reservation(params[:reservation])

      if @reservation.save
        flash[:success] = "NEW RESERVATION ADDED"
        redirect_to current_user
      else
        render 'new'
      end
    end

    def update

    end

    def set_user  #temp
      @user = User.find(params[:user_id])
    end

    private
      def build_reservation(reserv)
        room_res = reserv[:room_reservation]
        puts "-------------------------------------------------------------------------------------------------------"
        puts room_res
        arrival = Date.new room_res["start_date(1i)",].to_i, reserv["start_date(2i)",].to_i, reserv["start_date(3i)",].to_i
        depart = Date.new room_res["end_date(1i)",].to_i, reserv["end_date(2i)",].to_i, reserv["end_date(3i)",].to_i
        demands = reserv["client_demands"]

        current_user.reservations.build({start_date: arrival, end_date: depart, client_demands: demands})
      end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_filter :set_user
  load_and_authorize_resource

  def show
    @reservation = Reservation.find(@user.id)
  end

  def index
      @reservation = Reservation.find_all_by_user_id(@user.id)
  end

  def new
    @reservation = Reservation.new
    @room = Room.new
  end

  def create
    @reservation = build_reservation params[:reservation]

    if @reservation.save
      flash[:success] = "NEW RESERVATION ADDED"
      redirect_to my_profile_path
    else
      render 'new'
    end
  end

  def update

  end

  def set_user  #temp
    @user = current_user
  end

  private
    def build_reservation(reserv)

      arrival = Date.new reserv["start_date(1i)",].to_i, reserv["start_date(2i)",].to_i, reserv["start_date(3i)",].to_i
      depart = Date.new reserv["end_date(1i)",].to_i, reserv["end_date(2i)",].to_i, reserv["end_date(3i)",].to_i
      demands = reserv["client_demands"]

      current_user.reservations.build({start_date: arrival, end_date: depart, client_demands: demands})
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper

  def get_array_room_types
    test = {}
    RoomType.all.each do |rt|
      test.store(rt.id, rt.room_type)
    end
    return test
  end

  def get_today_date
    Date.strptime(Date.today.to_s, "%d-%m-%Y")
  end

  def get_selected_initialised_value(array, index)
    value= 0;
    if (array.count != 0)
      value = array[index]
    end

    value
  end

end

app/views/client/reservations/Search_form.html.haml
%body
  = form_tag(new_reservation_path) do
    #ReservationFormContent
      .container.room_search#ajout_chambre
        .roomNo#no FIND A ROOM?
        %table.table.table-borderless
          %tr
            %td{style: "border: none"}
              %b CHECK-IN :
              = text_field_tag "check_in", @check_in, placeholder: Date.today, required: true, autocomplete: :off
            %td{style: "border: none"}
              %b CHECK-OUT :
              = text_field_tag "check_out", @check_out, placeholder: Date.today + 3.days, required: true, autocomplete: :off
          %tr
            %td{style: "border: none"}
              %b TYPE :
              = select_tag "room_type", options_for_select(RoomType.all.map{|x| [x.room_type,  x.id]})
            %td{style: "border: none"}
              %b VIEW :
              = select_tag "view_type", options_for_select(ViewType.all.map{|x| [x.view_type,  x.id]})
              = hidden_field_tag :chosen_rooms, @chosen_rooms


        = submit_tag "FIND", class: "btn btn-default btn-edit-room"

    %br

    #hidden{style: "display: none"} RENDER HERE

.room_section.reserved
  %h5 Your Rooms :
  - if @chosen_rooms != nil
    = render partial: "client/reservations/room_list", locals: {rooms: @chosen_rooms}

.room_section.search_result
  %h5 Search Results :
  = render partial: "client/reservations/room_list", locals: {rooms: @rooms}


%br
%br



:javascript
  nb_rooms = 0;
  $(function() {
    setDatePicker()
  })

  setDatePicker = function() {
    $("#check_in").datepicker({
      format: 'yyyy-mm-dd'
    });
    $("#check_out").datepicker({
      format: 'yyyy-mm-dd'
    });
  }

  add_new_room_search = function() {
    div = $('#ajout_chambre').clone()
    div = change_attr(div)
    $('#ReservationFormContent').append(div)
    setDatePicker()
  }

  change_attr = function(div) {
    view_type = div.find('#rooms_'+ 0 +'view_type')
    room_type = div.find('#rooms_'+ 0 +'room_type')
    check_in = div.find('#rooms_'+ 0 +'check_in')
    check_out = div.find('#rooms_'+ 0 +'check_out')
    no = div.find('#no')
    nb_rooms++

    view_type.attr("name", "rooms[" + nb_rooms + "]view_type")
    view_type.attr("id", "rooms_"+ nb_rooms +"view_type")

    room_type.attr("name", "rooms[" + nb_rooms + "]room_type")
    room_type.attr("id", "rooms_"+ nb_rooms +"room_type")

    check_in.attr("name", "rooms[" + nb_rooms + "]check_in")
    check_in.attr("id", "rooms_"+ nb_rooms +"check_in")
    check_in[0].value=""

    check_out.attr("name", "rooms[" + nb_rooms + "]check_out")
    check_out.attr("id", "rooms_"+ nb_rooms +"check_out")
    check_out[0].value=""

    no[0].innerHTML= "ROOM NO. " +  (nb_rooms + 1)
    return div
  }

app/views/client/reservations/_btn_next_form.html.haml
.container
  - if @cpt_steps > 0
    = submit_tag "BACK", class: "btn btn-default form-btn-back", id: "btn-back-step"
  - if @cpt_steps < 5
    = submit_tag "NEXT", class: "btn btn-default form-btn", id: "btn-next-step"

app/views/client/reservations/_reservation_confirmation_form.html.haml
.container.form-section#step_confirm
  %h4.form-section-title
    FINAL STEP : CONFIRM RESERVATION?

  .form-section-content.confirmation-form
    .container  
      = form_tag(client_reservations_path, id: "form_confirmation") do 
        = hidden_field_tag :rooms, @chosen_rooms
        = hidden_field_tag :check_in, @check_in
        = hidden_field_tag :check_out, @check_out
        = hidden_field_tag :nb_rooms, @nb_rooms
        = hidden_field_tag :demands, @demands
        = submit_tag "RESERVE!", class: "btn btn-default form-btn-confirm"

app/views/client/reservations/_reservation_fifth_step.html.haml
.container.form-section#step_5
  %h4.form-section-title
    STEP #5 : Any special demands? (NO PROSTITUTES!)

  .form-section-content
    %table.table.row-reservation-form
      %tr
        %td{style: "border: none"}
          %b DEMANDS :
          = text_area_tag "demands", @demands, placeholder: "...", autocomplete: :off, class: "form-control", id: "demands"

app/views/client/reservations/_reservation_short.html.haml
.reservation-show
  .roomNo#no
    - no = @user.reservations.count - index
    = link_to "RESERVATION #" + (no).to_s, my_reservation_path(id: reservation.id)
  %table.table.table-borderless
    %tr
      %td{style: "border: none"}
        %b CHECK-IN :
        = reservation.room_reservations.first.start_date.to_date
      %td{style: "border: none"}
        %b CHECK-OUT :
        = reservation.room_reservations.first.end_date.to_date

app/views/client/reservations/_room_list.html.haml
%ul.room_list
  - rooms.each do |r|
    %li.room_show
      .room_image
        = image_tag(get_room_type_from_room(r).downcase + ".jpg", alt: get_room_type_from_room(r), size: "180x120")
      .room_info
        = r.room_no

      = form_tag(new_reservation_path) do
        = hidden_field_tag :added_room, r.id
        = hidden_field_tag :check_in, params[:check_in]
        = hidden_field_tag :check_out, params[:check_out]
        = hidden_field_tag :view_type, params[:view_type]
        = hidden_field_tag :room_type, params[:room_type]
        = hidden_field_tag :chosen_rooms, @chosen_rooms_ids
        = submit_tag "ADD ROOM"

app/views/client/reservations/my_new_test.html.haml
%body
  %p#notice= notice
  %h1.section_title RESERVATION

  = form_for(:my_reservation, url: client_reservations_path) do |form|
    #ReservationFormContent
      .container.room_choice#ajout_chambre
        .roomNo#no ROOM SEARCH
        %table.table.table-borderless
          %tr
            %td{style: "border: none"}
              %b CHECK-IN :
              = text_field_tag "rooms[0]check_in", nil, placeholder: Date.today, required: true, autocomplete: :off
            %td{style: "border: none"}
              %b CHECK-OUT :
              = text_field_tag "rooms[0]check_out", nil, placeholder: Date.today, required: true, autocomplete: :off
          %tr
            %td{style: "border: none"}
              %b TYPE :
              = select_tag "rooms[0]room_type", options_for_select(RoomType.all.map{|x| [x.room_type,  x.id]})
            %td{style: "border: none"}
              %b VIEW :
              = select_tag "rooms[0]view_type", options_for_select(ViewType.all.map{|x| [x.view_type,  x.id]})

        %a{:href => "#", onclick: "add_new_room_search()", class: "btn btn-default btn-edit-room"} SEARCH

    %br

    #room_section
    #hidden{style: "display: none"} RENDER HERE

    %br
    %br
    = form.submit "Create", class: "btn btn-default", confirm: "Are you sure?"



:javascript
  nb_rooms = 0;
  $(function() {
    setDatePicker()
  })

  setDatePicker = function() {
    $("#rooms_"+nb_rooms+"check_in").datepicker({
      format: 'yyyy-mm-dd'
    });
    $("#rooms_"+nb_rooms+"check_out").datepicker({
      format: 'yyyy-mm-dd'
    });
  }

  add_new_room_search = function() {
    div = $('#ajout_chambre').clone()
    div = change_attr(div)
    $('#ReservationFormContent').append(div)
    setDatePicker()
  }

  change_attr = function(div) {
    view_type = div.find('#rooms_'+ 0 +'view_type')
    room_type = div.find('#rooms_'+ 0 +'room_type')
    check_in = div.find('#rooms_'+ 0 +'check_in')
    check_out = div.find('#rooms_'+ 0 +'check_out')
    no = div.find('#no')
    nb_rooms++

    view_type.attr("name", "rooms[" + nb_rooms + "]view_type")
    view_type.attr("id", "rooms_"+ nb_rooms +"view_type")

    room_type.attr("name", "rooms[" + nb_rooms + "]room_type")
    room_type.attr("id", "rooms_"+ nb_rooms +"room_type")

    check_in.attr("name", "rooms[" + nb_rooms + "]check_in")
    check_in.attr("id", "rooms_"+ nb_rooms +"check_in")
    check_in[0].value=""

    check_out.attr("name", "rooms[" + nb_rooms + "]check_out")
    check_out.attr("id", "rooms_"+ nb_rooms +"check_out")
    check_out[0].value=""

    no[0].innerHTML= "ROOM NO. " +  (nb_rooms + 1)
    return div
  }

app/views/client/reservations/new.html.haml
%body
  %h2.profile-header MAKING A RESERVATION?
  = form_tag(new_reservation_path, id: "form_selection", remote: true) do
    = hidden_field_tag :cpt_steps, @cpt_steps
    = render partial: "client/reservations/reservation_first_step"

    .container
      = submit_tag "NEXT", class: "btn btn-default form-btn", id: "btn-next-step"



:javascript
  nb_rooms = 0;
  $(function() {
    setDatePicker()
  })

  setDatePicker = function() {
    $("#check_in").datepicker({
      format: 'yyyy-mm-dd'
    });
    $("#check_out").datepicker({
      format: 'yyyy-mm-dd'
    });
  }

  showNextStep = function() {
    $("#form_selection").submit()
  }

  changeFormTarget = function() {
    $("#form_selection")[0].action = "/client/reservations"
    $("#form_selection").attr("data-remote", "false")
    $("#form_selection").submit()
  }

  refreshNbRooms = function() {
    $("#btn-second-step")[0].value = "CHANGE"
  }

  hidebutton = function(cpt_steps) {
    $("#btn-first-step").remove() // verif dates valides!!
    $("#form_selection").submit()
  }

app/views/client/reservations/old_new.html.haml
%body
  %h1 RESERVATION
  = form_for(:my_reservation, url: client_reservations_path) do |form|
    #ReservationFormContent
      .container.room_choice#ajout_chambre
        .roomNo#no ROOM NO. 1
        %table.table.table-borderless
          %tr
            %td{style: "border: none"}
              %b CHECK-IN :
              = text_field_tag "rooms[0]check_in", nil, placeholder: Date.today, required: true, autocomplete: :off
            %td{style: "border: none"}
              %b CHECK-OUT :
              = text_field_tag "rooms[0]check_out", nil, placeholder: Date.today, required: true, autocomplete: :off
          %tr
            %td{style: "border: none"}
              %b TYPE :
              = select_tag "rooms[0]room_type", options_for_select(RoomType.all.map{|x| [x.room_type,  x.id]})
            %td{style: "border: none"}
              %b VIEW :
              = select_tag "rooms[0]view_type", options_for_select(ViewType.all.map{|x| [x.view_type,  x.id]})

    %br

    #hidden{style: "display: none"} RENDER HERE

    %a{:href => "#", onclick: "add_new_room_search()", class: "btn btn-default"} ADD
    %br
    %br
    = form.submit "Create", class: "btn btn-default", confirm: "Are you sure?"



:javascript
  nb_rooms = 0;
  $(function() {
    setDatePicker()
  })

  setDatePicker = function() {
    $("#rooms_"+nb_rooms+"check_in").datepicker({
      format: 'yyyy-mm-dd'
    });
    $("#rooms_"+nb_rooms+"check_out").datepicker({
      format: 'yyyy-mm-dd'
    });
  }

  add_new_room_search = function() {
    div = $('#ajout_chambre').clone()
    div = change_attr(div)
    $('#ReservationFormContent').append(div)
    setDatePicker()
  }

  change_attr = function(div) {
    view_type = div.find('#rooms_'+ 0 +'view_type')
    room_type = div.find('#rooms_'+ 0 +'room_type')
    check_in = div.find('#rooms_'+ 0 +'check_in')
    check_out = div.find('#rooms_'+ 0 +'check_out')
    no = div.find('#no')
    nb_rooms++

    view_type.attr("name", "rooms[" + nb_rooms + "]view_type")
    view_type.attr("id", "rooms_"+ nb_rooms +"view_type")

    room_type.attr("name", "rooms[" + nb_rooms + "]room_type")
    room_type.attr("id", "rooms_"+ nb_rooms +"room_type")

    check_in.attr("name", "rooms[" + nb_rooms + "]check_in")
    check_in.attr("id", "rooms_"+ nb_rooms +"check_in")
    check_in[0].value=""

    check_out.attr("name", "rooms[" + nb_rooms + "]check_out")
    check_out.attr("id", "rooms_"+ nb_rooms +"check_out")
    check_out[0].value=""

    no[0].innerHTML= "ROOM NO. " +  (nb_rooms + 1)
    return div
  }

app/views/client/reservations/test_new.html.haml
%body
  %p#notice= notice
  %h1.section_title RESERVATION

  = form_for(:my_reservation, url: client_reservations_path) do |form|
    #ReservationFormContent
      .container.room_choice#ajout_chambre
        .roomNo#no ROOM SEARCH
        %table.table.table-borderless
          %tr
            %td{style: "border: none"}
              %b CHECK-IN :
              = text_field_tag "rooms[0]check_in", nil, placeholder: Date.today, required: true, autocomplete: :off
            %td{style: "border: none"}
              %b CHECK-OUT :
              = text_field_tag "rooms[0]check_out", nil, placeholder: Date.today, required: true, autocomplete: :off
          %tr
            %td{style: "border: none"}
              %b TYPE :
              = select_tag "rooms[0]room_type", options_for_select(RoomType.all.map{|x| [x.room_type,  x.id]})
            %td{style: "border: none"}
              %b VIEW :
              = select_tag "rooms[0]view_type", options_for_select(ViewType.all.map{|x| [x.view_type,  x.id]})

        %a{:href => "#", onclick: "add_new_room_search()", class: "btn btn-default btn-edit-room"} SEARCH

    %br

    #hidden{style: "display: none"} RENDER HERE
    #room_section


    %br
    %br
    = form.submit "Create", class: "btn btn-default", confirm: "Are you sure?"



:javascript
  nb_rooms = 0;
  $(function() {
    setDatePicker()
  })

  setDatePicker = function() {
    $("#rooms_"+nb_rooms+"check_in").datepicker({
      format: 'yyyy-mm-dd'
    });
    $("#rooms_"+nb_rooms+"check_out").datepicker({
      format: 'yyyy-mm-dd'
    });
  }

  add_new_room_search = function() {
    div = $('#ajout_chambre').clone()
    div = change_attr(div)
    $('#ReservationFormContent').append(div)
    setDatePicker()
  }

  change_attr = function(div) {
    view_type = div.find('#rooms_'+ 0 +'view_type')
    room_type = div.find('#rooms_'+ 0 +'room_type')
    check_in = div.find('#rooms_'+ 0 +'check_in')
    check_out = div.find('#rooms_'+ 0 +'check_out')
    no = div.find('#no')
    nb_rooms++

    view_type.attr("name", "rooms[" + nb_rooms + "]view_type")
    view_type.attr("id", "rooms_"+ nb_rooms +"view_type")

    room_type.attr("name", "rooms[" + nb_rooms + "]room_type")
    room_type.attr("id", "rooms_"+ nb_rooms +"room_type")

    check_in.attr("name", "rooms[" + nb_rooms + "]check_in")
    check_in.attr("id", "rooms_"+ nb_rooms +"check_in")
    check_in[0].value=""

    check_out.attr("name", "rooms[" + nb_rooms + "]check_out")
    check_out.attr("id", "rooms_"+ nb_rooms +"check_out")
    check_out[0].value=""

    no[0].innerHTML= "ROOM NO. " +  (nb_rooms + 1)
    return div
  }